### PR TITLE
Evn validation 1403

### LINKED ISSUE #1403: Event name validation: Add regex validation so that people cannot submit the wrong event name
### Overview
We are having a problem where people are naming the meetings incorrectly. 

When the event name shows up on the website it shows up with the word meeting and the name of the project above it. So if someone puts the name of the project and the word meeting in the event name. We need to check for if they have the project name or the word meeting and gently remind them to not include it in the event name. 

### Action Items
- [ ] Check for the use of the project name, and the word "meeting" or "MTG" in the event name. 
- [ ] If either is present display a gentle reminder "Please do not use the project name or the word 'meeting' in the Event Name"
    - make it look nice.. (feel free to reach out to design @juliagab56 )

### Resources
- #1409

__________________________

Notice in the picture below the meeting name is just "Design" not "VRMS Design Meeting"

Screen Shot 2023-06-27 at 5 07 06 PM

### PR DESCRIPTION
**Pull request by evanyang1**
Fixes #1403 

### What changes did you make and why did you make them ?

  -  When editing the event, the names will be validated. If the meeting contains 'meeting', 'mtg', or the project name itself, the validation code will reject those changes.
  - I wrote a new util function that serves the task: It returns true if a string contains any of the 'words' in an array.
  -

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

<details>

</details>

### CODE REVIEW

**Comment by trillium** [comment]
Hey Evan,

Can you add a bit of context on the changes you've made to the codebase and why they've been made?

I know that we have the issue markes, and that you've referenced them within this PR, but it's good practice to put a summary together so that whoever is reviewing it has an easier time following along with the changes you've submitted.

File: client/src/components/manageProjects/utilities/validateEventForm.js [hunk 1]
```diff
@@ -1,13 +1,24 @@
...
   let newErrors = {};
   Object.keys(vals).forEach((key) => {
     switch (key) {
       case 'name':
         // Required
         if (!vals[key]) {
           newErrors = { ...newErrors, name: 'Event name is required' };
+        } else if (
+          isWordInArrayInString(
+            ['meeting', 'mtg', projectToEdit.name.toLowerCase()],
```
Comment (trillium) [inline client/src/components/manageProjects/utilities/validateEventForm.js:14]: Nitpick but you don't need to pass in `.toLowerCase()` since then utils function you made already does that text transform

File: client/src/components/manageProjects/utilities/validateEventForm.js [hunk 2]
```diff
@@ -1,19 +1,24 @@
 import validator from 'validator';
-import { isAnySubstring } from './../../../utils/stringUtils.js';
-import { useProjectsStore } from '../../../store/projectStore.js';
+import { isWordInArrayInString } from './../../../utils/stringUtils.js';
 
-const validateEventForm = (vals) => {
+const validateEventForm = (vals, projectToEdit) => {
```
Comment (trillium) [inline client/src/components/manageProjects/utilities/validateEventForm.js:4]: `CreateNewEvent()` fails because of this line

One solve is to have projectToEdit default to null `(vals, projectToEdit = null) =>`

File: client/src/components/manageProjects/utilities/validateEventForm.js [hunk 3]
```diff
@@ -1,19 +1,24 @@
...
   Object.keys(vals).forEach((key) => {
     switch (key) {
       case 'name':
         // Required
         if (!vals[key]) {
           newErrors = { ...newErrors, name: 'Event name is required' };
-        } else if (isAnySubstring(['meeting', 'mtg'], vals[key])) {
+        } else if (
+          isWordInArrayInString(
+            ['meeting', 'mtg', projectToEdit.name.toLowerCase()],
```
Comment (trillium) [inline client/src/components/manageProjects/utilities/validateEventForm.js:14]: If using the above `projectToEdit = null` then you will also need to test this line to see if `projectToEdit` was suppied:
```js
['meeting', 'mtg', projectToEdit && projectToEdit.name.toLowerCase()]
```

**Review by trillium — CHANGES_REQUESTED** [review]

**Comment by evanyang1** [comment]
@Spiteless I used a slightly different approach to address your comments. I tested it and it works still.

**Review by jbubar — APPROVED** [review]
This is great! I pulled it and it looks good
<details>
    <summary>pic of it live</summary>

Screen Shot 2023-07-27 at 4 11 25 PM


</details>

**Comment by trillium** [comment]
Hey @evanyang1 , looks like merging is blocked becasue I requested changes and haven't come back yet to remove that change request. My bad.

Combing back through the PR I see that you addressed getting the form submission issue that was cropping up.

Looks like edits to `yarn.lock` are still in this pull request, can you please remove those, the changes you've made shouldn't effect that file

**Comment by evanyang1** [comment]
Ok that should do the trick.

**Comment by trillium** [comment]
Great job, thanks for rebasing and dropping yarn lock. We've got a few PRs that all tackle this similar issue so stitching them together will be it's own beast, but this code works. Thanks @evanyang1 !

**Review by trillium — APPROVED** [review]

**Comment by trillium** [comment]
Looking for a few more eyes on this if someone else has time. I'm happy with it's current state

**Review by MattPereira — APPROVED** [review]
@evanyang1 well done sanitizing the meeting name input according to the requirements of the issue!
