### PR TITLE
Recurring event 1351 bug fix

### LINKED ISSUE #1351: Bugs when updating a recurring event
### Overview
Users are reporting two bugs with updating a recurring event for a project. First, it is not possible to change a recurring event description to be empty if it was previously filled. Second, attempting to update a recurring event name, description, or link fails if that event has a previously existing duration of `.5`

<details><summary>See screenshot of meeting update failure for .5 duration</summary>

image

</details>

### Action Items
- [x] Create a new recurring event for one of the projects on [dev.vrms.io](https://dev.vrms.io) with the description field filled with some text
    - [x] Attempt to update the event to have no description text
- [x] Create a new recurring event with a duration of `.5`
    - [x] Attempt to update any of the event information besides duration
- [x] Allow for event description to be updated from filled to an empty string
- [x] Allow for events with an existing duration of `.5` to have their information updated without throwing a `Cannot calculate end time` error

### Instructions
- We want users to be able to change a meeting time from having a description to having no description ( an empty string ).
- We want users to be able to change name, description, link, ect. for meetings that have a duration of `.5`

### Resources
- User comments about the bugs
    - https://github.com/hackforla/VRMS/issues/1178#issuecomment-1464368613
    - https://github.com/hackforla/VRMS/issues/1178#issuecomment-1464431644
    - https://github.com/hackforla/VRMS/issues/1178#issuecomment-1464938029
- Relevant components to explore
    1. [editMeetingTimes](https://github.com/hackforla/VRMS/blob/development/client/src/components/manageProjects/editMeetingTimes.js)
    2. [editableMeeting](https://github.com/hackforla/VRMS/blob/development/client/src/components/manageProjects/editableMeeting.js)
    3. [editProject](https://github.com/hackforla/VRMS/blob/development/client/src/components/manageProjects/editProject.js)

### PR DESCRIPTION
**Pull request by vanessavun**
Fixes #1351 

### What changes did you make and why did you make them?

  - Refactored the `addDurationToTime.js` file which had 8 hardcoded switch statements that did not include a statement for any "0.5" inputted time. The file now has one line of the same formula and any duration will return a new Date object. Any invalid inputs will result an Error.
  - Added an additional conditional statement to include blank descriptions when editing meeting details. If it previously had a description and the user wants to leave it blank, the blank description will be carried over with the update.
  - Added a Jest test file for the `addDurationToTime.js` file to ensure that the formula works.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screenshot code changes)

<details>
<summary>Visuals before and after for blank descriptions</summary>

blank

</details>

<details>
<summary>Visuals before and after for half-hour meetings</summary>
  
halfhour

</details>

### CODE REVIEW

File: client/src/components/manageProjects/editMeetingTimes.js [hunk 1]
```diff
@@ -39,7 +39,8 @@ const EditMeetingTimes = ({
         };
       }
 
-      if (values.description) {
+      //if there is a description or a blank description
+      if (values.description || !values.description) {
```
Comment (MattPereira) [inline client/src/components/manageProjects/editMeetingTimes.js:43]: Help us understand why the if statement is necessary here? Wouldn't this conditional just always evaluate to `true` ?

**Review by MattPereira — APPROVED** [review]
Amazing work @vanessavun :tada: 

Users will finally be able to create and update meeting times with a duration of 30 minutes! 

Loved that refactor of the gross switch statement and well done going above and beyond with the testing :muscle: 

Feel free to merge whenever you like!

File: client/src/components/manageProjects/editMeetingTimes.js (hunk 1 above)
Comment (vanessavun) [reply client/src/components/manageProjects/editMeetingTimes.js:43]: Yes, it needs to always be true so the description is carried over with the update. When there is a blank description, the original conditional, `if (values.description)`, will be falsy so the blank description doesn't get updated. I guess there is a better way to rewrite this file in which we do a catch all to update all the values like:
`theUpdatedEvent = {
          ...theUpdatedEvent,
          **value name: updated value**
};`

**Comment by plang-psm** [comment]
Will take a peak at this tomorrow but it looks super clean from a quick skim!

File: client/src/components/manageProjects/utilities/addDurationToTime.js
Comment (MicahBear) [inline client/src/components/manageProjects/utilities/addDurationToTime.js:1]: Removed 30+ lines of code of hard-coded cases  💯

**Comment by trillium** [comment]
Seriously great work figuring this one out. Well done :)

**Review by MicahBear — APPROVED** [review]
Creating a test case for this is a great addition.

**Review by plang-psm — APPROVED** [review]
