### PR TITLE
1802 Gave superadmin admin privilages too

### LINKED ISSUE #1802: Fix Super Admin User Login issue
### Overview
After implementing the Super Admin User feature in #1747, we identified a bug where the Super Admin User (vrms-admin-perm@hackforla.org) is unable to log in to VRMS. This issue tracks the fix for this bug.

### Past Research
<details><summary>Bug summary from Jack Haeger_2024-10-17</summary>
<p>

Trillium merged the [Super User PR](https://github.com/hackforla/VRMS/pull/1765), rebuilt Dev, and edited the DB to make [vrms-admin-perm@hackforla.org](mailto:vrms-admin-perm@hackforla.org) a super user.

The good news is that almost everything is working as expected (the user screen is grayed out and no other admin users can edit this user).

The bad news is that we cannot log in with this user to [dev.vrms.io](http://dev.vrms.io/):
- When we go to log in with that user ([vrms-admin-perm@hackforla.org](mailto:vrms-admin-perm@hackforla.org)) we are unable to log in and we receive the error message “We don’t recognize your email address. Please, create an account.”
- I can confirm that this account already existed due to the fact that 1) the account shows up in [dev.VRMS.io](http://dev.vrms.io/), and 2) the account’s email inbox received VRMS magic links to log in to the [dev.vrms.io](http://dev.vrms.io/) website on September 16, so it clearly existed and was logging in appropriately.
- Also, this email address logs in as expected on PROD.
Screenshot 2024-10-17 at 3 24 47 PM (1)

</p>
</details> 

<details><summary>Nikhil's research_2024-10-22</summary>
<p>

The checkAuth Method has authOrigin Set to LOG_IN
image (3)

It fetches SIGN_IN
image (4)

Which is exposed by this route
image (5)

That router works in this way
and it checks for a method called verifyUser.isAdminByEmai
image (6)

And voila
image (7)

if (role === 'admin' || user.managedProjects.length > 0)
It is allowing either "admin"
or someone who has managedProjects.length>0

Now if we look at the super user
Neither are they "admin" and their "managedProjects" empty
So they are not able to log in
image (8)

But when you see Trillium's profile, Jack Haeger told me that when converting Trillium to super-user, he was still able to log in because the managedProjects list is not empty!
image (9)

</p>
</details> 

### Action Items
- [ ] Implement Nikhil's proposed fix below: 

```js
change user.middleware.js to
const { User } = require('../models');
function checkDuplicateEmail(req, res, next) {
  User.findOne({ email: req.body.email }).then((user) => {
    if (user) {
      return res.sendStatus(400);
    }
    next();
  });
}
function isAdminByEmail(req, res, next) {
  User.findOne({ email: req.body.email }).then((user) => {
    if (!user) {
      return res.sendStatus(400);
    } else {
      const role = user.accessLevel;
      if (role === 'admin' || role ==='superadmin' ||  user.managedProjects.length > 0) {
        next();
      } else {
        next(res.sendStatus(401));
      }
    }
  });
}
const verifyUser = {
  checkDuplicateEmail,
  isAdminByEmail,
};
module.exports = verifyUser;
```
- [ ] Test if fix is successful by logging into Dev with vrms-admin-perm@hackforla.org
  - [ ] If fix worked, the "Success" message will be displayed and a VRMS Login link will be sent to the inbox of vrms-admin-perm@hackforla.org
  - [ ] If fix fails, the error message will be displayed under the email name: "We don't recognize your email address. Please, create an account."  

<details><summary>"Success" Screenshot</summary>
<p>

Screenshot 2024-10-22 at 1 34 16 PM

</p>
</details> 

<details><summary>Error message screenshot</summary>
<p>

Screenshot 2024-10-17 at 3 24 47 PM (1)

</p>
</details> 

### Resources/Instructions
- This issue is part of this epic: #1737

### PR DESCRIPTION
**Pull request by ntrehan**
Fixes #1802

### What changes did you make and why did you make them ?

  - Gave all privileges existing for admins to superadmins 

### Screenshots of Proposed Changes Of The Website  
<details>
<summary>Visuals before changes are applied</summary>

image

</details>

<details>
<summary>Visuals after changes are applied</summary>
 
image

</details>

### CODE REVIEW

**Comment by JackHaeg** [comment]
@trillium Please review this PR when you have a moment.

**Comment by JackHaeg** [comment]
Hi @trillium Can you please take a look at this PR when you have a moment? Once this PR is reviewed/merged, we can unblock releasing the User Permission Search feature to PROD.

**Comment by jng34** [comment]
@trillium @ntrehan @JackHaeg 
After cloning down the target branch, I made sure to pull the latest changes from the branch using `git pull origin 1802-v2`. 
I ran into this issue when running `yarn start` (see picture). It says `error: cannot find module 'express'`, even though express is clearly in the `package.json` file. Also, I tried deleting all the `node_module` folders and `package-lock.json` files, and ran `npm install` again but to no avail. 

Any thoughts or suggestions to resolve this?

image

**Comment by jng34** [comment]
I was able to resolve the issue after referring to the VRMS documentation.

**Comment by JackHaeg** [comment]
Hi @trillium & @ntrehan! When you have a moment, do you have any pointers that you could share with @jng34 on how to resolve the issue he described above 👆?

File: client/src/components/Navbar.jsx [hunk 1]
```diff
@@ -59,7 +59,7 @@ const Navbar = (props) => {
             </>
           )}
           {/* Admin auth -> Displays 2 links -> 'Users' and 'Projects'. */}
-          {auth?.user?.accessLevel === 'admin' && (
+          {auth?.user?.accessLevel === 'admin' || auth?.user?.accessLevel == 'superadmin' && (
```
Comment (jng34) [inline client/src/components/Navbar.jsx]: The `Navbar` did not render after logging in. This is because the logic is missing parentheses:
`{(auth?.user?.accessLevel === 'admin' || auth?.user?.accessLevel === 'superadmin') && (...`

**Comment by jng34** [comment]
> Hi @trillium & @ntrehan! When you have a moment, do you have any pointers that you could share with @jng34 on how to resolve the issue he described above 👆?

Issue resolved. All is good.

File: client/src/pages/ProjectList.jsx [hunk 2]
```diff
@@ -40,12 +40,12 @@ export default function ProjectList({ auth }) {
...
         let projectData;
 
-        if(user?.accessLevel === 'admin') {
+        if(user?.accessLevel === 'admin' || user?.accessLevel === 'superadmin') {
           projectData = await projectApiService.fetchProjects();
         }
 
         // if user is not admin, but is a project manager, only show projects they manage
-        if (user?.accessLevel !== 'admin' && user?.managedProjects.length > 0) {
+        if (user?.accessLevel !== 'admin' && user?.accessLevel !== 'superadmin' && user?.managedProjects.length > 0) {
```
Comment (jng34) [inline client/src/pages/ProjectList.jsx]: The logic should also include parentheses and use the OR operator here otherwise this conditional statement might evaluate to false and not render.

`if ((user?.accessLevel !== 'admin' || user?.accessLevel !== 'superadmin') && user?.managedProjects.length > 0) {`

**Review by jng34 — DISMISSED** [review]
Aside from the parentheses needed in the logical statements, everything else looks good!

**Comment by JackHaeg** [comment]
**Updates based on All Team call:**
- @ntrehan To review / implement changes suggested by @jng34. 
- @trillium will also take a look at this PR

File: client/src/components/Navbar.jsx (hunk 1 above)
Comment (ntrehan) [reply client/src/components/Navbar.jsx]: Hi @jng34 
Thanks for pointing that out
Have fixed this and I do see the navbar
image
Please confirm if you can see the same after the new commit

File: client/src/pages/ProjectList.jsx (hunk 2 above)
Comment (ntrehan) [reply client/src/pages/ProjectList.jsx]: Hi @jng34 Thanks for pointing that out
Please check the fix on your end
I see the Project List now
image

File: client/src/components/Navbar.jsx (hunk 1 above)
Comment (jng34) [reply client/src/components/Navbar.jsx]: Looks good!

**Review by trillium — APPROVED** [review]
Looking good to me, I double chcked if there were any other instances of `admin` that needed to be checked agaist `superadmin` too and didn't see any!
